// @generated by scripts/generate-contracts.mjs; do not edit.
// schema-bundle-sha256: c54de738993a231bdf15fdf158ec8821e4a667fc716cce0902ef28e01c3f26ad
#![allow(clippy::module_name_repetitions, clippy::struct_excessive_bools)]

use serde::{Deserialize, Serialize};

pub const CONTRACT_SCHEMA_BUNDLE_SHA256: &str =
    "c54de738993a231bdf15fdf158ec8821e4a667fc716cce0902ef28e01c3f26ad";

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum MemoryRecordStatus {
    #[serde(rename = "proposed")]
    Proposed,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "disabled")]
    Disabled,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum MemoryRecordKind {
    #[serde(rename = "preference")]
    Preference,
    #[serde(rename = "routine")]
    Routine,
    #[serde(rename = "boundary")]
    Boundary,
    #[serde(rename = "biographical")]
    Biographical,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct MemoryRecord {
    pub schema_version: String,
    pub memory_id: String,
    pub status: MemoryRecordStatus,
    pub kind: MemoryRecordKind,
    pub content: String,
    pub confidence: f64,
    pub source_session_id: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub approved_at: Option<String>,
    pub last_used_at: Option<String>,
    pub enabled: bool,
    pub revision: u64,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum PlaybackEventType {
    #[serde(rename = "state_changed")]
    StateChanged,
    #[serde(rename = "track_changed")]
    TrackChanged,
    #[serde(rename = "capabilities_changed")]
    CapabilitiesChanged,
    #[serde(rename = "source_disconnected")]
    SourceDisconnected,
    #[serde(rename = "user_override")]
    UserOverride,
    #[serde(rename = "program_interrupted")]
    ProgramInterrupted,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum PlaybackEventReason {
    #[serde(rename = "adapter_update")]
    AdapterUpdate,
    #[serde(rename = "user_command")]
    UserCommand,
    #[serde(rename = "session_lost")]
    SessionLost,
    #[serde(rename = "session_replaced")]
    SessionReplaced,
    #[serde(rename = "user_media_key")]
    UserMediaKey,
    #[serde(rename = "tts_resume_aborted")]
    TtsResumeAborted,
    #[serde(rename = "media_error")]
    MediaError,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum PlaybackStateSourceKind {
    #[serde(rename = "local")]
    Local,
    #[serde(rename = "system_session")]
    SystemSession,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum PlaybackStateStatus {
    #[serde(rename = "disconnected")]
    Disconnected,
    #[serde(rename = "idle")]
    Idle,
    #[serde(rename = "loading")]
    Loading,
    #[serde(rename = "playing")]
    Playing,
    #[serde(rename = "paused")]
    Paused,
    #[serde(rename = "stopped")]
    Stopped,
    #[serde(rename = "error")]
    Error,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PlaybackStateCapabilities {
    pub play: bool,
    pub pause: bool,
    pub seek: bool,
    pub next: bool,
    pub previous: bool,
    pub set_queue: bool,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum PlaybackStateTrackOrigin {
    #[serde(rename = "local")]
    Local,
    #[serde(rename = "system_session")]
    SystemSession,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PlaybackStateTrack {
    pub track_id: String,
    pub title: String,
    pub artist: Option<String>,
    pub album: Option<String>,
    pub artwork_uri: Option<String>,
    pub origin: PlaybackStateTrackOrigin,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PlaybackStateSafeError {
    pub error_id: String,
    pub safe_message: String,
    pub retryable: bool,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PlaybackState {
    pub schema_version: String,
    pub source_id: String,
    pub source_kind: PlaybackStateSourceKind,
    pub status: PlaybackStateStatus,
    pub capabilities: PlaybackStateCapabilities,
    pub current_track: Option<PlaybackStateTrack>,
    pub position_ms: u64,
    pub duration_ms: Option<u64>,
    pub revision: u64,
    pub updated_at: String,
    pub last_error: Option<PlaybackStateSafeError>,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct PlaybackEvent {
    pub schema_version: String,
    pub event_id: String,
    pub sequence: u64,
    pub r#type: PlaybackEventType,
    pub occurred_at: String,
    pub source_id: String,
    pub state_revision: u64,
    pub reason: Option<PlaybackEventReason>,
    pub state: Option<PlaybackState>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ProgramPlanMode {
    #[serde(rename = "local")]
    Local,
    #[serde(rename = "system_session")]
    SystemSession,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProgramPlanTrackSegment {
    pub r#type: String,
    pub segment_id: String,
    pub track_id: String,
    pub segue_text: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ProgramPlanVoiceSegmentTrigger {
    #[serde(rename = "opening")]
    Opening,
    #[serde(rename = "between_tracks")]
    BetweenTracks,
    #[serde(rename = "user_message")]
    UserMessage,
    #[serde(rename = "track_changed")]
    TrackChanged,
    #[serde(rename = "closing")]
    Closing,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProgramPlanVoiceSegment {
    pub r#type: String,
    pub segment_id: String,
    pub text: String,
    pub trigger: ProgramPlanVoiceSegmentTrigger,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(untagged)]
pub enum ProgramPlanSegmentsItem {
    TrackSegment(ProgramPlanTrackSegment),
    VoiceSegment(ProgramPlanVoiceSegment),
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProgramPlan {
    pub schema_version: String,
    pub program_id: String,
    pub source_id: String,
    pub mode: ProgramPlanMode,
    pub created_at: String,
    pub segments: Vec<ProgramPlanSegmentsItem>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ProviderErrorErrorId {
    #[serde(rename = "ERR-1301")]
    Err1301,
    #[serde(rename = "ERR-1302")]
    Err1302,
    #[serde(rename = "ERR-1303")]
    Err1303,
    #[serde(rename = "ERR-1304")]
    Err1304,
    #[serde(rename = "ERR-1305")]
    Err1305,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ProviderErrorCategory {
    #[serde(rename = "authentication")]
    Authentication,
    #[serde(rename = "rate_limit")]
    RateLimit,
    #[serde(rename = "timeout")]
    Timeout,
    #[serde(rename = "unavailable")]
    Unavailable,
    #[serde(rename = "invalid_response")]
    InvalidResponse,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ProviderError {
    pub schema_version: String,
    pub error_id: ProviderErrorErrorId,
    pub provider: String,
    pub category: ProviderErrorCategory,
    pub retryable: bool,
    pub retry_after_ms: Option<u64>,
    pub safe_message: String,
    pub occurred_at: String,
    pub correlation_id: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ScheduleRuleDaysOfWeekItem {
    #[serde(rename = "mon")]
    Mon,
    #[serde(rename = "tue")]
    Tue,
    #[serde(rename = "wed")]
    Wed,
    #[serde(rename = "thu")]
    Thu,
    #[serde(rename = "fri")]
    Fri,
    #[serde(rename = "sat")]
    Sat,
    #[serde(rename = "sun")]
    Sun,
}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ScheduleRule {
    pub schema_version: String,
    pub schedule_id: String,
    pub name: String,
    pub timezone: String,
    pub days_of_week: Vec<ScheduleRuleDaysOfWeekItem>,
    pub local_time: String,
    pub enabled: bool,
    pub notification_only: bool,
    pub created_at: String,
    pub updated_at: String,
    pub revision: u64,
}
