// @generated by scripts/generate-contracts.mjs; do not edit.
// schema-bundle-sha256: c54de738993a231bdf15fdf158ec8821e4a667fc716cce0902ef28e01c3f26ad

export const CONTRACT_SCHEMA_BUNDLE_SHA256 = "c54de738993a231bdf15fdf158ec8821e4a667fc716cce0902ef28e01c3f26ad" as const;

export interface MemoryRecord {
  readonly schemaVersion: "1.0.0";
  readonly memoryId: string;
  readonly status: "proposed" | "approved" | "disabled";
  readonly kind: "preference" | "routine" | "boundary" | "biographical";
  readonly content: string;
  readonly confidence: number;
  readonly sourceSessionId: null | string;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly approvedAt: null | string;
  readonly lastUsedAt: null | string;
  readonly enabled: boolean;
  readonly revision: number;
}

export interface PlaybackEvent {
  readonly schemaVersion: "1.0.0";
  readonly eventId: string;
  readonly sequence: number;
  readonly type: "state_changed" | "track_changed" | "capabilities_changed" | "source_disconnected" | "user_override" | "program_interrupted";
  readonly occurredAt: string;
  readonly sourceId: string;
  readonly stateRevision: number;
  readonly reason: null | "adapter_update" | "user_command" | "session_lost" | "session_replaced" | "user_media_key" | "tts_resume_aborted" | "media_error";
  readonly state: null | PlaybackState;
}

export interface PlaybackState {
  readonly schemaVersion: "1.0.0";
  readonly sourceId: string;
  readonly sourceKind: "local" | "system_session";
  readonly status: "disconnected" | "idle" | "loading" | "playing" | "paused" | "stopped" | "error";
  readonly capabilities: PlaybackStateCapabilities;
  readonly currentTrack: null | PlaybackStateTrack;
  readonly positionMs: number;
  readonly durationMs: null | number;
  readonly revision: number;
  readonly updatedAt: string;
  readonly lastError: null | PlaybackStateSafeError;
}

export interface PlaybackStateCapabilities {
  readonly play: boolean;
  readonly pause: boolean;
  readonly seek: boolean;
  readonly next: boolean;
  readonly previous: boolean;
  readonly setQueue: boolean;
}

export interface PlaybackStateTrack {
  readonly trackId: string;
  readonly title: string;
  readonly artist: null | string;
  readonly album: null | string;
  readonly artworkUri: null | string;
  readonly origin: "local" | "system_session";
}

export interface PlaybackStateSafeError {
  readonly errorId: string;
  readonly safeMessage: string;
  readonly retryable: boolean;
}

export interface ProgramPlan {
  readonly schemaVersion: "1.0.0";
  readonly programId: string;
  readonly sourceId: string;
  readonly mode: "local" | "system_session";
  readonly createdAt: string;
  readonly segments: ReadonlyArray<ProgramPlanTrackSegment | ProgramPlanVoiceSegment>;
}

export interface ProgramPlanTrackSegment {
  readonly type: "track";
  readonly segmentId: string;
  readonly trackId: string;
  readonly segueText: null | string;
}

export interface ProgramPlanVoiceSegment {
  readonly type: "voice";
  readonly segmentId: string;
  readonly text: string;
  readonly trigger: "opening" | "between_tracks" | "user_message" | "track_changed" | "closing";
}

export interface ProviderError {
  readonly schemaVersion: "1.0.0";
  readonly errorId: "ERR-1301" | "ERR-1302" | "ERR-1303" | "ERR-1304" | "ERR-1305";
  readonly provider: string;
  readonly category: "authentication" | "rate_limit" | "timeout" | "unavailable" | "invalid_response";
  readonly retryable: boolean;
  readonly retryAfterMs: null | number;
  readonly safeMessage: string;
  readonly occurredAt: string;
  readonly correlationId: string;
}

export interface ScheduleRule {
  readonly schemaVersion: "1.0.0";
  readonly scheduleId: string;
  readonly name: string;
  readonly timezone: string;
  readonly daysOfWeek: ReadonlyArray<"mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun">;
  readonly localTime: string;
  readonly enabled: boolean;
  readonly notificationOnly: true;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly revision: number;
}

export type ContractDocument = MemoryRecord | PlaybackEvent | PlaybackState | ProgramPlan | ProviderError | ScheduleRule;
